# Generated by Django 4.2.7 on 2023-11-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('tl', models.URLField(max_length=255, unique=True, verbose_name='URL')),
                ('cpv', models.CharField(blank=True, max_length=255, verbose_name='CPV')),
                ('v', models.FloatField(blank=True, verbose_name='Очікувана вартість закупівлі')),
                ('a', models.DateTimeField(blank=True, null=True, verbose_name='Дата оголошення процедури')),
                ('s', models.CharField(max_length=255, unique=True, verbose_name='Поточний статус процедури')),
                ('t_id', models.CharField(max_length=255, unique=True, verbose_name='Ідентифікатор закупівлі')),
                ('cdb', models.CharField(max_length=255, unique=True, verbose_name='Організатор закупівлі')),
                ('t_method', models.CharField(max_length=255, unique=True, verbose_name='Процедура закупівлі')),
            ],
            options={
                'verbose_name': 'Tenderу',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-a'],
            },
        ),
    ]
