# Generated by Django 4.2.7 on 2023-11-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='cdb',
            field=models.CharField(max_length=255, verbose_name='Організатор закупівлі'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='s',
            field=models.CharField(max_length=255, verbose_name='Поточний статус процедури'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='t_method',
            field=models.CharField(max_length=255, verbose_name='Процедура закупівлі'),
        ),
    ]
