# Generated by Django 4.2.7 on 2023-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0002_alter_tender_cdb_alter_tender_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='s',
            field=models.CharField(blank=True, max_length=255, verbose_name='Поточний статус процедури'),
        ),
    ]
