# Generated by Django 4.2.7 on 2023-11-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0003_alter_tender_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='t',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
