# Generated by Django 4.2.7 on 2023-11-12 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0004_alter_tender_t'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-a'], 'verbose_name': 'Тендер', 'verbose_name_plural': 'Тендери'},
        ),
    ]
