# Generated by Django 4.2.7 on 2023-11-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0005_alter_tender_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіон',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('edrpou', models.CharField(max_length=20, unique=True, verbose_name='ЕДРПОУ')),
                ('crt_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoda.region')),
            ],
        ),
    ]
