# Generated by Django 4.2.7 on 2023-11-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0006_region_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='region',
            new_name='region_id',
        ),
    ]
