# Generated by Django 4.2.7 on 2023-11-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0008_rename_region_id_agency_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Установа', 'verbose_name_plural': 'Установи'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регіон', 'verbose_name_plural': 'Регіони'},
        ),
        migrations.RemoveField(
            model_name='agency',
            name='crt_date',
        ),
    ]
