# Generated by Django 4.2.7 on 2023-11-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0009_alter_agency_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='edr',
            field=models.ForeignKey(default='00022504', on_delete=django.db.models.deletion.CASCADE, to='zoda.agency', to_field='edrpou'),
        ),
    ]
