# Generated by Django 4.2.7 on 2023-11-12 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0010_tender_edr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='edr',
            field=models.ForeignKey(default='00022504', on_delete=django.db.models.deletion.CASCADE, to='zoda.agency', to_field='edrpou', verbose_name='Код ЄДРПОУ'),
        ),
    ]
