# Generated by Django 4.2.7 on 2023-11-12 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoda', '0011_alter_tender_edr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoda.region', verbose_name='Регіон'),
        ),
    ]
