--
-- PostgreSQL database dump
--

-- Dumped from database version 12.12
-- Dumped by pg_dump version 12.12

-- Started on 2023-11-13 03:09:11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 17346)
-- Name: zoda_agency; Type: TABLE; Schema: public; Owner: zoda
--

CREATE TABLE public.zoda_agency (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    edrpou character varying(20) NOT NULL,
    region_id bigint NOT NULL
);


ALTER TABLE public.zoda_agency OWNER TO zoda;

--
-- TOC entry 225 (class 1259 OID 17344)
-- Name: zoda_agency_id_seq; Type: SEQUENCE; Schema: public; Owner: zoda
--

ALTER TABLE public.zoda_agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zoda_agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2883 (class 0 OID 17346)
-- Dependencies: 226
-- Data for Name: zoda_agency; Type: TABLE DATA; Schema: public; Owner: zoda
--

INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (2, 'Департамент житлово-комунального господарства та будівництва Запорізької обласної державної адміністрації', '33836176', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (4, 'Департамент з питань цивільного захисту населення Запорізької обласної державної адміністрації', '14373165', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (9, 'Управління зовнішніх зносин та зовнішньоекономічної діяльності Запорізької обласної державної адміністрації', '25971041', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (10, 'Управління містобудування та архітектури Запорізької обласної державної адміністрації', '35258283', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (11, 'Департамент захисту довкілля Запорізької обласної державної адміністрації', '43847544', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (12, 'Департамент внутрішньої політики та інформаційної діяльності Запорізької обласної державної адміністрації', '34718647', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (13, 'Відділ внутрішнього аудиту Запорізької обласної державної адміністрації', '38732555', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (15, 'Служба у справах дітей Запорізької обласної державної адміністрації', '25765784', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (16, 'Управління молоді, фізичної культури та спорту Запорізької обласної державної адміністрації', '38922191', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (18, 'Управління оборонної роботи та взаємодії з правоохоронними органами Запорізької обласної державної адміністрації', '45021701', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (19, 'Управління транспорту та зв’язку Запорізької обласної державної адміністрації (реорганізовується в Департамент інфраструктури та промисловості з 01.11.2023)', '44638516', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (20, 'Управління стратегічних галузей виробництва Запорізької обласної державної адміністрації (ліквідується з 01.11.2023)', '44574751', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (27, 'Запорізька районна державна адміністрація Запорізької області', '20488417', 3);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (28, 'Відділ фінансів Запорізької районної державної адміністрації Запорізької області', '20488432', 3);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (30, 'Служба у справах дітей Запорізької районної державної адміністрації Запорізької області', '34157121', 3);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (31, 'Відділ освіти, охорони здоров''''я, культури і спорту Запорізької районної державної адміністрації Запорізької області', '25218792', 3);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (34, 'Служба у справах дітей  Мелітопольської районної державної адміністрації    Запорізької області', '35432646', 4);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (0, 'Запорізька обласна державна адміністрація (апарат)', '00022504', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (5, 'Департамент соціального захисту населення Запорізької обласної державної адміністрації', '03193005', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (6, 'Департамент освіти і науки Запорізької обласної державної адміністрації', '02143429', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (7, 'Департамент охорони здоров''я Запорізької обласної державної адміністрації', '02012869', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (14, 'Державний архів Запорізької області', '03494617', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (17, 'Департамент фінансів Запорізької обласної державної адміністрації', '02313714', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (21, 'Бердянська районна державна адміністрація', '02140840', 1);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (22, 'Відділ фінансів Бердянської районної державної адміністрації', '02313803', 1);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (23, 'Управління соціального захисту населення Бердянської районної державної адміністрації', '03193181', 1);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (38, 'Архівний відділ Пологівської районної державної адміністрації Запорізької області', '44251875', 5);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (40, 'Служба у справах дітей Пологівської районної державної адміністрації Запорізької області', '25219811', 5);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (1, 'Департамент економічного розвитку і торгівлі Запорізької обласної державної адміністрації', '02741456', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (3, 'Департамент агропромислового розвитку Запорізької обласної державної адміністрації', '00731270', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (8, 'Департамент культури, туризму, національностей та релігій Запорізької обласної державної адміністрації', '02228109', 0);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (24, 'Василівська районна державна адміністрація Запорізької області', '02140857', 2);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (25, 'Відділ фінансів Василівської районної державної адміністрації Запорізької області', '02313861', 2);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (26, 'Управління соціального захисту населення  Василівської районної державної адміністрації Запорізької області', '03193117', 2);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (29, 'Управління соціального захисту населення Запорізької районної державної адміністрації Запорізької області', '03193241', 3);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (32, 'Мелітопольська районна державна адміністрація Запорізької області', '02126314', 4);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (33, 'Управління соціального захисту населення  Мелітопольської районної державної адміністрації Запорізької області', '03193057', 4);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (35, 'Відділ фінансів Мелітопольської районної державної адміністрації Запорізької області', '02313648', 4);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (36, 'Відділ, освіти, охорони здоров''''я, культури та спорту  Мелітопольської районної державної адміністрації Запорізької області', '02136100', 4);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (37, 'Пологівська районна державна адміністрація Запорізької області', '02126354', 5);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (39, 'Фінансовий відділ Пологівської районної державної адміністрації Запорізької області', '02313708', 5);
INSERT INTO public.zoda_agency (id, name, edrpou, region_id) VALUES (41, 'Управління соціального захисту населення Пологівської районної державної адміністрації Запорізької області', '03193123', 5);


--
-- TOC entry 2889 (class 0 OID 0)
-- Dependencies: 225
-- Name: zoda_agency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: zoda
--

SELECT pg_catalog.setval('public.zoda_agency_id_seq', 1, false);


-- Completed on 2023-11-13 03:09:11

--
-- PostgreSQL database dump complete
--

